### ISSUE TITLE
排序单独使用无效

### ISSUE THREAD

**Issue by youuycom** [pagehelper/Mybatis-PageHelper#110]
单独使用startPage有效.
单独使用orderBy没有效果.
两个一起使用是有效果的.
PageHelper.startPage(1, 10);
PageHelper.orderBy("sort asc, id asc");

**Comment by abel533** [comment]
order by 确实无效，并且还会 count，已经解决了，会发布一个 5.1.2版本。

**Comment by ChanaLii** [comment]
单独使用orderBy，sql使用 if 函数后台会抛异常
1) java代码
`    @Override
    public List<Clerk> findClerkList(Map<String, Object> params) {
        PageHelper.startPage(((Integer) params.get("pageNum")),
                ((Integer) params.get("pageSize")));
        if (params.containsKey("orderBy")) {
            if (!StringUtil.empty(params.get("orderBy").toString())) {
                PageHelper.orderBy(params.get("orderBy").toString());
        }
        }
        List<Clerk> clerkList = clerkMapper.findClerkList(params);
        return clerkList;
    }`
2) sql语句
`SELECT  
  1                                              AS all_apply_customer,  
  count(if(xataa.accept_status = 1, TRUE, NULL)) AS accept_apply_customer,  
  count(if(xataa.accept_status = 0, TRUE, NULL)) AS reject_apply_customer,  
  count(if(xataa.accept_status = 2, TRUE, NULL)) AS invalid_apply_customer  
FROM xft_apply_task_assign_agent xataa  
ORDER BY all_apply_customer DESC  `
3) 执行sql后台抛异常
`Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 3, column 11.  
Was expecting one of:  
    <EOF>   
    "AS" ...  
    "DO" ...  
    "INTO" ...  
    "FROM" ...  
    "WHERE" ...  
    "XML" ...  
    "GROUP" ...  
    "VALUE" ...  
    "HAVING" ...  
    "REPLACE" ...  
    "TRUNCATE" ...  
    "CAST" ...  
    "PARTITION" ...  
    "EXTRACT" ...  
    "MATERIALIZED" ... `

[点击查看异常详情](http://blog.csdn.net/weixin_36146275/article/details/79355544)
