### ISSUE TITLE
大数据量的问题

### ISSUE THREAD

**Issue by JerryFoundation** [pagehelper/Mybatis-PageHelper#308]
用pagehelper插件如何支持大数据量的分页呢？ 比如我的limit是 100000,10这种， 那么pagehelper拼接的查询就会非常的慢， 是否有更好的支持？

**Comment by piaoxuew** [comment]
我也遇到同样的问题，10万条数据，每页10条，分了1万多页，页面越大，查询速度越慢。你解决了吗？

**Comment by piaoxuew** [comment]
> 用pagehelper插件如何支持大数据量的分页呢？ 比如我的limit是 100000,10这种， 那么pagehelper拼接的查询就会非常的慢， 是否有更好的支持？
我也遇到同样的问题，10万条数据，每页10条，分了1万多页，页面越大，查询速度越慢。你解决了吗？

**Comment by linhaismail** [comment]
我不知道为什么会收到邮件～～说一下我的解决办法。大数据量不要用这个插件。如果是app端展示，只有下一页，不需指定页码，则直接根据上一条的最后一条记录，where后字段加索引，limit pagesize。如果是必须指定页码，则单查出所需页面的所有id，然后根据id查询数据，in (1,2,3) 或 union all 都比较快。可以测试一下，效果很好。发自坚果 Pro 2
* body { padding:0 16px 30px !important; margin:0 !important;background-color: #ffffff; line-height: 1.4;word-wrap: break-word; word-break: normal; } div {word-wrap: break-word; word-break: normal; } p {word-wrap: break-word; word-break: normal; text-indent: 0pt !important; } span {word-wrap: break-word; word-break: normal; } a {word-wrap: break-word; word-break: normal; } td {word-wrap: break-word; word-break: break-all; }piaoxuew <notifications@github.com>
于 2019年3月30日 下午2:30写道：
用pagehelper插件如何支持大数据量的分页呢？ 比如我的limit是 100000,10这种， 那么pagehelper拼接的查询就会非常的慢， 是否有更好的支持？
我也遇到同样的问题，10万条数据，每页10条，分了1万多页，页面越大，查询速度越慢。你解决了吗？


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pagehelper/Mybatis-PageHelper","title":"pagehelper/Mybatis-PageHelper","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/pagehelper/Mybatis-PageHelper"}},"updates":{"snippets":[{"icon":"PERSON","message":"@piaoxuew in #308: \u003e 用pagehelper插件如何支持大数据量的分页呢？ 比如我的limit是 100000,10这种， 那么pagehelper拼接的查询就会非常的慢， 是否有更好的支持？\r\n我也遇到同样的问题，10万条数据，每页10条，分了1万多页，页面越大，查询速度越慢。你解决了吗？\r\n"}],"action":{"name":"View Issue","url":"https://github.com/pagehelper/Mybatis-PageHelper/issues/308#issuecomment-478213007"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pagehelper/Mybatis-PageHelper/issues/308#issuecomment-478213007",
"url": "https://github.com/pagehelper/Mybatis-PageHelper/issues/308#issuecomment-478213007",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by piaoxuew** [comment]
> 我不知道为什么会收到邮件～～说一下我的解决办法。大数据量不要用这个插件。如果是app端展示，只有下一页，不需指定页码，则直接根据上一条的最后一条记录，where后字段加索引，limit pagesize。如果是必须指定页码，则单查出所需页面的所有id，然后根据id查询数据，in (1,2,3) 或 union all 都比较快。可以测试一下，效果很好。发自坚果 Pro 2 * body { padding:0 16px 30px !important; margin:0 !important;background-color: #ffffff; line-height: 1.4;word-wrap: break-word; word-break: normal; } div {word-wrap: break-word; word-break: normal; } p {word-wrap: break-word; word-break: normal; text-indent: 0pt !important; } span {word-wrap: break-word; word-break: normal; } a {word-wrap: break-word; word-break: normal; } td {word-wrap: break-word; word-break: break-all; }piaoxuew <notifications@github.com> 于 2019年3月30日 下午2:30写道： 用pagehelper插件如何支持大数据量的分页呢？ 比如我的limit是 100000,10这种， 那么pagehelper拼接的查询就会非常的慢， 是否有更好的支持？ 我也遇到同样的问题，10万条数据，每页10条，分了1万多页，页面越大，查询速度越慢。你解决了吗？ —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread. {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pagehelper/Mybatis-PageHelper","title":"pagehelper/Mybatis-PageHelper","subtitle":"GitHub repository","main_image_url":"[https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open](https://github.githubassets.com/images/email/message_cards/header.png%22,%22avatar_image_url%22:%22https://github.githubassets.com/images/email/message_cards/avatar.png%22,%22action%22:%7B%22name%22:%22Open) in GitHub","url":"[https://github.com/pagehelper/Mybatis-PageHelper"}},"updates":{"snippets":[{"icon":"PERSON","message":"@piaoxuew](https://github.com/pagehelper/Mybatis-PageHelper%22%7D%7D,%22updates%22:%7B%22snippets%22:%5B%7B%22icon%22:%22PERSON%22,%22message%22:%22@piaoxuew) in #308: \u003e 用pagehelper插件如何支持大数据量的分页呢？ 比如我的limit是 100000,10这种， 那么pagehelper拼接的查询就会非常的慢， 是否有更好的支持？\r\n我也遇到同样的问题，10万条数据，每页10条，分了1万多页，页面越大，查询速度越慢。你解决了吗？\r\n"}],"action":{"name":"View Issue","url":"[#308 (comment)](https://github.com/pagehelper/Mybatis-PageHelper/issues/308#issuecomment-478213007)"}}} [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#308 (comment)](https://github.com/pagehelper/Mybatis-PageHelper/issues/308#issuecomment-478213007)", "url": "[#308 (comment)](https://github.com/pagehelper/Mybatis-PageHelper/issues/308#issuecomment-478213007)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

我换了个环境测试，用同一个数据库，发现在idea里面JDK1.8的环境下，没有这个问题，这就尴尬了，不知道问题出在哪儿。

**Comment by piaoxuew** [comment]
和jdk的环境也没有关系，我换成了jar，用1.6 1.7 均没有问题，这就搞笑了。。。。

**Comment by piaoxuew** [comment]
问题已解决，最终发现是xml文件里面的换行导致的，目前还没仔细调试mybatis的源码，为啥xml文件的换行会导致速度变慢，这个问题很奇怪。

**Comment by piaoxuew** [comment]
插件没有任何问题。
